ci: fix syntax error

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,6 +34,7 @@ jobs:
   promote-images:
     needs: detect-changes
     if: ${{ needs.detect-changes.outputs.apps != '' && toJSON(fromJSON(needs.detect-changes.outputs.apps)) != '[]' }}
+    runs-on: ubuntu-latest
     strategy:
       matrix:
         app: ${{ fromJSON(needs.detect-changes.outputs.apps) }}
@@ -70,6 +71,7 @@ jobs:
 
   deploy:
     needs: [detect-changes, promote-images]
+    runs-on: ubuntu-latest
     strategy:
       matrix:
         app: ${{ fromJSON(needs.detect-changes.outputs.apps) }}
@@ -79,40 +81,41 @@ jobs:
     steps:
       - name: Deploy to server
         uses: appleboy/scp-action@v1
-        host: ${{ secrets.SERVER_HOST }}
-        username: ${{ secrets.SERVER_USERNAME }}
-        key: ${{ secrets.SERVER_KEY }}
-        script: |
-          set -e
+        with:
+          host: ${{ secrets.SERVER_HOST }}
+          username: ${{ secrets.SERVER_USERNAME }}
+          key: ${{ secrets.SERVER_KEY }}
+          script: |
+            set -e
 
-          cd ~/deploy/todo-docker || {
-            echo "Project directory not found. Cloning repository . . ."
-            git clone https://github.com/mupinnn/todo-docker.git ~/deploy/todo-docker
-            cd ~/deploy/todo-docker
-          }
+            cd ~/deploy/todo-docker || {
+              echo "Project directory not found. Cloning repository . . ."
+              git clone https://github.com/mupinnn/todo-docker.git ~/deploy/todo-docker
+              cd ~/deploy/todo-docker
+            }
 
-          git pull origin main || true
+            git pull origin main || true
 
-          # Login to GHCR
-          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+            # Login to GHCR
+            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
 
-          # Pull related image
-          docker pull ${{ env.REGISTRY }}/${{ github.event.repository.name }}/${{ matrix.app }}:${{ github.sha }}
+            # Pull related image
+            docker pull ${{ env.REGISTRY }}/${{ github.event.repository.name }}/${{ matrix.app }}:${{ github.sha }}
 
-          if [[ "${{ matrix.app }}" == "api" ]]; then
-            docker pull ${{ env.REGISTRY }}/${{ github.event.repository.name}}/migrate:${{ github.sha }}
-          fi
+            if [[ "${{ matrix.app }}" == "api" ]]; then
+              docker pull ${{ env.REGISTRY }}/${{ github.event.repository.name}}/migrate:${{ github.sha }}
+            fi
 
-          echo "Preparing environment variables . . ."
-          echo "${{ secrets.ENV_ROOT }}" > .env
+            echo "Preparing environment variables . . ."
+            echo "${{ secrets.ENV_ROOT }}" > .env
 
-          mkdir -p apps/web
-          echo "${{ secrets.ENV_WEB }}" > ./apps/web/.env
+            mkdir -p apps/web
+            echo "${{ secrets.ENV_WEB }}" > ./apps/web/.env
 
-          mkdir -p apps/api
-          echo "${{ secrets.ENV_API }}" > ./apps/api/.env
+            mkdir -p apps/api
+            echo "${{ secrets.ENV_API }}" > ./apps/api/.env
 
-          echo "Restarting services . . ."
-          docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --no-build --force-recreate
+            echo "Restarting services . . ."
+            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --no-build --force-recreate
 
-          docker image prune -f
+            docker image prune -f
